/* Generated by Together */

package smartClient.framework;
import java.rmi.*;
import java.util.Properties;
import java.net.*;

/**
 * Title:        Smart Client Framework<br>
 * Copyright:    Copyright (c) Steve McDaniel<br>
 * Company:      Smart Client Framework inc.<br>
 * @author Steve McDaniel
 * @version 1.0
 */
public class Client
{

	private ServerInterface getServer()
    {
    	try
        {
		    Properties properties = SmartClientFramework.getSingleton().getProperties();
		    String serverName = (String) properties.get( "SOS_SERVER_NAME" );
			String registryURL = (String) properties.get( "REGISTRY_URL" );
		    return (ServerInterface) Naming.lookup( registryURL + serverName );
        }
        catch( RemoteException exception )
        {
        	System.out.println( exception );
        	exception.printStackTrace();
        }
        catch( NotBoundException exception )
        {
        	System.out.println( exception );
        	exception.printStackTrace();
        }
        catch( MalformedURLException exception )
        {
        	System.out.println( exception );
        	exception.printStackTrace();
        }
        return null;
    }

	public SessionInterface createSession( )
    {
    	try
        {
        	return (SessionInterface) getServer().createSession();
        }
        catch( RemoteException exception )
        {
        	System.out.println( exception );
        	exception.printStackTrace();
        }
        return null;
    }

	public static void main( String []args )
    {
    	try
        {
		    if (args.length == 0)
		    {
		      System.out.println("You should provide properties file :"
		                 + "c:\\jdk1.3.1\\bin\\java Keyboard.clientBusinessObjects.Client SOSProperties.txt");
		      System.exit(0);
		    }
		    SmartClientFramework.getSingleton().setPropertiesUsing( args[0] );
	        Client aClient = new Client();
		    ServerInterface theServer = (ServerInterface) aClient.getServer();
	        System.out.println( theServer.greetings() );
	        SessionInterface aSession = (SessionInterface) aClient.createSession();
	        System.out.println( aSession.greetings() );
	        System.out.println( "Hello. I'm the Client. My middleware framework thinks it's on the " + SmartClientFramework.getSingleton().whereAmI() + ".");
        }
        catch( RemoteException exception )
        {
        	System.out.println( exception );
        	exception.printStackTrace();
        }
    }
}
