/* Generated by Together */

package smartClient.framework;

import java.util.*;
import model.*;

/**
 * Title:        Smart Client Framework<br>
 * Copyright:    Copyright (c) Steve McDaniel<br>
 * Company:      Smart Client Framework inc.<br>
 * @author Steve McDaniel
 * @version 1.0
 */
public class Propagator
{
	private Visitor delegator;
    private Object attributeOwner;
    private String attributeName;
    private Class elementType;
	private Collection nonTransitionedMembers;

	public Propagator()
    {
    	nonTransitionedMembers = (Collection) new ArrayList();
    }

	public Propagator( Visitor _delegator, Object _attributeOwner, String _attributeName, Class _elementType )
    {
    	this();
    	delegator = _delegator;
        attributeOwner = _attributeOwner;
        attributeName = _attributeName;
        elementType = _elementType;
    }

	protected Visitor getDelegator()
    {
    	return delegator;
    }

	protected Object getAttributeOwner()
    {
    	return attributeOwner;
    }

	protected String getAttributeName()
    {
    	return attributeName;
    }

	protected Class getElementType()
    {
    	return elementType;
    }

	protected Collection getNonTransitionedMembers()
    {
    	return nonTransitionedMembers;
    }
}
