/* Generated by Together */

package smartClient.framework;

import java.rmi.*;
import java.rmi.server.*;

/**
 * Title:        Smart Client Framework<br>
 * Copyright:    Copyright (c) Steve McDaniel<br>
 * Company:      Smart Client Framework inc.<br>
 * @author Steve McDaniel
 * @version 1.0
 */
public class RMISession extends Session
{

  	public RMISession() throws RemoteException
    {
    }

  public void clearDB() throws RemoteException
    {
    	SmartClientFramework.getSingleton().clear();
    }

}
