/* Generated by Together */

package smartClient.framework;

import java.rmi.*;

/**
 * Title:        Smart Client Framework<br>
 * Copyright:    Copyright (c) Steve McDaniel<br>
 * Company:      Smart Client Framework inc.<br>
 * @author Steve McDaniel
 * @version 1.0
 */
public interface ServerInterface extends Remote
{
	public String greetings( ) throws RemoteException;
    public SessionInterface createSession() throws RemoteException;
}
