/* Generated by Together */

package smartClient.framework;

import java.rmi.*;
import java.rmi.server.*;

/**
 * Title:        Smart Client Framework<br>
 * Copyright:    Copyright (c) Steve McDaniel<br>
 * Company:      Smart Client Framework inc.<br>
 * @author Steve McDaniel
 * @version 1.0
 */
public class Server extends UnicastRemoteObject implements ServerInterface
{

	public Server() throws RemoteException
    {
    }

	public String greetings() throws RemoteException
    {
    	return "Hello. I'm the Server. My middleware framework thinks it's on the " + SmartClientFramework.getSingleton().whereAmI() + ".";
    }

	public SessionInterface createSession() throws RemoteException
    {
    	return (SessionInterface) SmartClientFramework.getSingleton().getPersistencePolicy().createSession();
    }
}


