/* Generated by Together */

package smartClient.framework;

/**
 * Title:        Smart Client Framework<br>
 * Copyright:    Copyright (c) Steve McDaniel<br>
 * Company:      Smart Client Framework inc.<br>
 * @author Steve McDaniel
 * @version 1.0
 */
public class SimpleIDFactory implements IDFactoryInterface
{
  private long previousTime = 0;
  private long nextTime = 0;

  public long nextId()
  {
    while( previousTime == nextTime )
    {
      nextTime = System.currentTimeMillis();
    }
    previousTime = nextTime;
    return nextTime;
  }

  public static void main(String[] args)
  {
    SimpleIDFactory anIDFactory = new SimpleIDFactory();
    long []gather = new long[7];
    for( int i=0; i < 7; i++ )
    {
      gather[i] = anIDFactory.nextId();
    }
    for( int i=0; i < 7; i++ )
    {
      System.out.println( gather[i] );
    }
  }
}
