/* Generated by Together */

package smartClient.framework;

import junit.framework.*;
import junit.extensions.*;


/**
 * Title:        Smart Client Framework<br>
 * Copyright:    Copyright (c) Steve McDaniel<br>
 * Company:      Smart Client Framework inc.<br>
 * @author Steve McDaniel
 * @version 1.0
 */
public class TestAll extends TestCase
{
    public TestAll( String name )
    {
        super( name );
    }

  public static void oneTimeSetUp()
  {
		SmartClientFramework.getSingleton().setPropertiesUsing( "C:\\sos3\\SOSProperties.txt" );
        SmartClientFramework.getSingleton().establishCommunications();
  }

    public static Test suite()
    {
    	TestSuite aSuite = new TestSuite();
        aSuite.addTest( smartClient.framework.TestAllTransient.suite() );
        aSuite.addTest( smartClient.framework.TestVisitorPersistence.suite() );
        aSuite.addTest( smartClient.framework.TestVisitorPersistenceOrphansOnly.suite() );
        aSuite.addTest( smartClient.framework.TestVisitorPersistenceCouplesOnly.suite() );
        aSuite.addTest( smartClient.framework.TestVisitorUniRetrievalClamps.suite() );
        aSuite.addTest( smartClient.framework.TestVisitorUniStorageClamps.suite() );

	    TestSetup wrapper = new TestSetup(aSuite)
	    {
	      public void setUp()
	      {
	        oneTimeSetUp();
	      }
	    };
	    return wrapper;
    }
}
