/* Generated by Together */

package smartClient.framework;

import junit.framework.*;
import junit.extensions.*;

/**
 * Title:        Smart Client Framework<br>
 * Copyright:    Copyright (c) Steve McDaniel<br>
 * Company:      Smart Client Framework inc.<br>
 * @author Steve McDaniel
 * @version 1.0
 */
public class TestAllTransient extends TestCase
{
    public TestAllTransient( String name )
    {
        super( name );
    }

  public static void oneTimeSetUp()
  {
		SmartClientFramework.getSingleton().setPropertiesUsing( "C:\\sos3\\SOSProperties.txt" );
        SmartClientFramework.getSingleton().establishCommunications();
  }

    public static Test suite()
    {
    	TestSuite aSuite = new TestSuite();
        aSuite.addTest( smartClient.framework.TestAccessMethodNameGenerator.suite() );
        aSuite.addTest( smartClient.framework.TestVisitor.suite() );
        aSuite.addTest( smartClient.framework.TestRoleKey.suite() );
        aSuite.addTest( smartClient.framework.TestOneToOneRepository.suite() );
        aSuite.addTest( smartClient.framework.TestToManyRepository.suite() );
        aSuite.addTest( smartClient.framework.TestUnidirectionalToManyRepository.suite() );
        aSuite.addTest( smartClient.framework.TestOneToManyRepository.suite() );
        aSuite.addTest( smartClient.framework.TestManyToManyRepository.suite() );
        aSuite.addTest( smartClient.framework.TestOneToOne.suite() );
        aSuite.addTest( smartClient.framework.TestOneToMany.suite() );
        aSuite.addTest( smartClient.framework.TestManyToMany.suite() );

	    TestSetup wrapper = new TestSetup(aSuite)
	    {
	      public void setUp()
	      {
	        oneTimeSetUp();
	      }
	    };
	    return wrapper;
    }
}
