/* Generated by Together */

package smartClient.framework;

/**
 * Title:        Smart Client Framework<br>
 * Copyright:    Copyright (c) Steve McDaniel<br>
 * Company:      Smart Client Framework inc.<br>
 * @author Steve McDaniel
 * @version 1.0
 */

public class VisitorFullToString extends VisitorFullPrinter
{

	private StringBuffer objectGraph = new StringBuffer();

	public void outputString( String pieceOfGraph )
	{
		objectGraph.append( pieceOfGraph );
	}

	public String toString()
    {
    	return objectGraph.toString();
    }

	public boolean equals( Object another )
	{
    	return toString().equals( another.toString() );
	}

	public int hashCode()
    {
    	return toString().hashCode();
    }

}
