/* generated by emit_jrmi(Oct 25 2000) on 11/22/00 at 05:00:03 PM from Keyboard.odl
*/

package Keyboard;

public class _TVSessionBeanHome_TVSessionBean_Tie extends org.omg.stub.javax.ejb._EJBHomeImpl_Tie {

	private Keyboard.TVSessionBeanHome _target = null;

	public java.lang.String[] _ids() {
		return _type_ids;
	}

	public void setTarget(java.rmi.Remote target) {
		_target = (Keyboard.TVSessionBeanHome) target;
		super.setTarget(target);
	}
	private static final java.lang.String[] _type_ids = {
		"RMI:Keyboard.TVSessionBeanHome:0000000000000000",
		"RMI:javax.ejb.EJBHome:0000000000000000"
	};

	public org.omg.CORBA.portable.OutputStream  _invoke(java.lang.String _method, org.omg.CORBA.portable.InputStream _in, org.omg.CORBA.portable.ResponseHandler _reply) throws org.omg.CORBA.SystemException {
		try {
				if (_method.equals("createTVSessionBean")) {
					Keyboard.TVSessionBeanObject _zz;
					try {
						_zz = _target.create();
					} catch(javax.ejb.CreateException ex) {
						org.omg.CORBA.portable.OutputStream _out = _reply.createExceptionReply();
						_out.write_string("IDL:javax/ejb/CreateEx:1.0");
						((org.omg.CORBA_2_3.portable.OutputStream)_out).write_value(ex, javax.ejb.CreateException.class);
						return _out;
					}
					org.omg.CORBA.portable.OutputStream _out = _reply.createReply();
					javax.rmi.CORBA.Util.writeRemoteObject(_out, _zz);
					return _out;
				}
		} catch (org.omg.CORBA.SystemException ex) {
			throw ex;
		} catch (java.lang.Throwable ex) {
			throw new org.omg.CORBA.portable.UnknownException(ex);
		}
		return super._invoke(_method, _in, _reply);
	}
}
