/* generated by emit_jrmi(Oct 25 2000) on 11/22/00 at 05:00:03 PM from Keyboard.odl
*/

package Keyboard;

public class _TVSessionBeanHome_Stub extends org.omg.stub.javax.ejb._EJBHome_Stub implements Keyboard.TVSessionBeanHome {

	private static final java.lang.String[] _type_ids = {
		"RMI:Keyboard.TVSessionBeanHome:0000000000000000",
		"RMI:javax.ejb.EJBHome:0000000000000000"
	};

	public java.lang.String[] _ids() {
		return _type_ids;
	}

	public Keyboard.TVSessionBeanObject create() throws java.rmi.RemoteException, javax.ejb.CreateException {
		org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("createTVSessionBean", Keyboard.TVSessionBeanHome.class);
		if (_so != null) {
			try {
				return ((Keyboard.TVSessionBeanHome)_so.servant).create();
			} finally {
				_servant_postinvoke(_so);
			}
		}
		org.omg.CORBA.portable.InputStream _in = null;
		try {
			org.omg.CORBA.portable.OutputStream _out = _request("createTVSessionBean", true);
			_in = _invoke(_out);
			Keyboard.TVSessionBeanObject _zz = (Keyboard.TVSessionBeanObject)_in.read_Object(Keyboard._TVSessionBeanObject_Stub.class);
			return _zz;
		} catch (org.omg.CORBA.portable.ApplicationException _ex) {
			org.omg.CORBA.portable.InputStream exIn = _ex.getInputStream();
			java.lang.String exId = _ex.getId();
			if (exId.equals("IDL:javax/ejb/CreateEx:1.0")) {
				exIn.read_string();
				throw (javax.ejb.CreateException)((org.omg.CORBA_2_3.portable.InputStream)exIn).read_value(javax.ejb.CreateException.class);
			}
			throw new java.rmi.UnexpectedException(exId);
		} catch (org.omg.CORBA.SystemException _ex) {
			throw javax.rmi.CORBA.Util.mapSystemException(_ex);
		} catch (org.omg.CORBA.portable.RemarshalException _ex) {
			return create();
		} finally {
			_releaseReply(_in);
		}
	}
}
