/* generated by emit_jrmi(Dec 21 2000) on 04/19/01 at 09:56:08 AM from Keyboard.odl
*/

package Keyboard;

public class _TVSessionBeanObject_Stub extends org.omg.stub.javax.ejb._EJBObject_Stub implements Keyboard.TVSessionBeanObject {

	private static final java.lang.String[] _type_ids = {
		"RMI:Keyboard.TVSessionBeanObject:0000000000000000",
		"RMI:javax.ejb.EJBObject:0000000000000000"
	};

	public java.lang.String[] _ids() {
		return _type_ids;
	}

	public String greeting() throws java.rmi.RemoteException, javax.ejb.EJBException {
		org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("greeting", Keyboard.TVSessionBeanObject.class);
		if (_so != null) {
			try {
				return ((Keyboard.TVSessionBeanObject)_so.servant).greeting();
			} finally {
				_servant_postinvoke(_so);
			}
		}
		org.omg.CORBA.portable.InputStream _in = null;
		try {
			org.omg.CORBA.portable.OutputStream _out = _request("greeting", true);
			_in = _invoke(_out);
			String _zz = _in.read_string();
			return _zz;
		} catch (org.omg.CORBA.portable.ApplicationException _ex) {
			org.omg.CORBA.portable.InputStream exIn = _ex.getInputStream();
			java.lang.String exId = _ex.getId();
			if (exId.equals("IDL:javax/ejb/EJBEx:1.0")) {
				exIn.read_string();
				throw (javax.ejb.EJBException)((org.omg.CORBA_2_3.portable.InputStream)exIn).read_value(javax.ejb.EJBException.class);
			}
			throw new java.rmi.UnexpectedException(exId);
		} catch (org.omg.CORBA.SystemException _ex) {
			throw javax.rmi.CORBA.Util.mapSystemException(_ex);
		} catch (org.omg.CORBA.portable.RemarshalException _ex) {
			return greeting();
		} finally {
			_releaseReply(_in);
		}
	}

	public void storeAll(byte[] objectGraph) throws java.rmi.RemoteException, javax.ejb.EJBException {
		org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("storeAll", Keyboard.TVSessionBeanObject.class);
		if (_so != null) {
			try {
				((Keyboard.TVSessionBeanObject)_so.servant).storeAll(objectGraph);
				return;
			} finally {
				_servant_postinvoke(_so);
			}
		}
		try {
			org.omg.CORBA.portable.OutputStream _out = _request("storeAll", true);
			_ByteArray_write(_out, objectGraph);
			_invoke(_out);
		} catch (org.omg.CORBA.portable.ApplicationException _ex) {
			org.omg.CORBA.portable.InputStream exIn = _ex.getInputStream();
			java.lang.String exId = _ex.getId();
			if (exId.equals("IDL:javax/ejb/EJBEx:1.0")) {
				exIn.read_string();
				throw (javax.ejb.EJBException)((org.omg.CORBA_2_3.portable.InputStream)exIn).read_value(javax.ejb.EJBException.class);
			}
			throw new java.rmi.UnexpectedException(exId);
		} catch (org.omg.CORBA.SystemException _ex) {
			throw javax.rmi.CORBA.Util.mapSystemException(_ex);
		} catch (org.omg.CORBA.portable.RemarshalException _ex) {
			storeAll(objectGraph);
		}
	}

	public void testCreateOne() throws java.rmi.RemoteException, javax.ejb.EJBException {
		org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("testCreateOne", Keyboard.TVSessionBeanObject.class);
		if (_so != null) {
			try {
				((Keyboard.TVSessionBeanObject)_so.servant).testCreateOne();
				return;
			} finally {
				_servant_postinvoke(_so);
			}
		}
		try {
			org.omg.CORBA.portable.OutputStream _out = _request("testCreateOne", true);
			_invoke(_out);
		} catch (org.omg.CORBA.portable.ApplicationException _ex) {
			org.omg.CORBA.portable.InputStream exIn = _ex.getInputStream();
			java.lang.String exId = _ex.getId();
			if (exId.equals("IDL:javax/ejb/EJBEx:1.0")) {
				exIn.read_string();
				throw (javax.ejb.EJBException)((org.omg.CORBA_2_3.portable.InputStream)exIn).read_value(javax.ejb.EJBException.class);
			}
			throw new java.rmi.UnexpectedException(exId);
		} catch (org.omg.CORBA.SystemException _ex) {
			throw javax.rmi.CORBA.Util.mapSystemException(_ex);
		} catch (org.omg.CORBA.portable.RemarshalException _ex) {
			testCreateOne();
		}
	}

	public void testCreateAll() throws java.rmi.RemoteException, javax.ejb.EJBException {
		org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("testCreateAll", Keyboard.TVSessionBeanObject.class);
		if (_so != null) {
			try {
				((Keyboard.TVSessionBeanObject)_so.servant).testCreateAll();
				return;
			} finally {
				_servant_postinvoke(_so);
			}
		}
		try {
			org.omg.CORBA.portable.OutputStream _out = _request("testCreateAll", true);
			_invoke(_out);
		} catch (org.omg.CORBA.portable.ApplicationException _ex) {
			org.omg.CORBA.portable.InputStream exIn = _ex.getInputStream();
			java.lang.String exId = _ex.getId();
			if (exId.equals("IDL:javax/ejb/EJBEx:1.0")) {
				exIn.read_string();
				throw (javax.ejb.EJBException)((org.omg.CORBA_2_3.portable.InputStream)exIn).read_value(javax.ejb.EJBException.class);
			}
			throw new java.rmi.UnexpectedException(exId);
		} catch (org.omg.CORBA.SystemException _ex) {
			throw javax.rmi.CORBA.Util.mapSystemException(_ex);
		} catch (org.omg.CORBA.portable.RemarshalException _ex) {
			testCreateAll();
		}
	}

	public byte[] retrieveAll(long seedID, String seedClass) throws java.rmi.RemoteException, javax.ejb.EJBException {
		org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("retrieveAll", Keyboard.TVSessionBeanObject.class);
		if (_so != null) {
			try {
				return ((Keyboard.TVSessionBeanObject)_so.servant).retrieveAll(seedID, seedClass);
			} finally {
				_servant_postinvoke(_so);
			}
		}
		org.omg.CORBA.portable.InputStream _in = null;
		try {
			org.omg.CORBA.portable.OutputStream _out = _request("retrieveAll", true);
			_out.write_longlong(seedID);
			_out.write_string(seedClass);
			_in = _invoke(_out);
			byte[] _zz = _ByteArray_read(_in);
			return _zz;
		} catch (org.omg.CORBA.portable.ApplicationException _ex) {
			org.omg.CORBA.portable.InputStream exIn = _ex.getInputStream();
			java.lang.String exId = _ex.getId();
			if (exId.equals("IDL:javax/ejb/EJBEx:1.0")) {
				exIn.read_string();
				throw (javax.ejb.EJBException)((org.omg.CORBA_2_3.portable.InputStream)exIn).read_value(javax.ejb.EJBException.class);
			}
			throw new java.rmi.UnexpectedException(exId);
		} catch (org.omg.CORBA.SystemException _ex) {
			throw javax.rmi.CORBA.Util.mapSystemException(_ex);
		} catch (org.omg.CORBA.portable.RemarshalException _ex) {
			return retrieveAll(seedID, seedClass);
		} finally {
			_releaseReply(_in);
		}
	}

	public byte[] retrieveAllFromStub(byte[] stub) throws java.rmi.RemoteException, javax.ejb.EJBException {
		org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("retrieveAllFromStub", Keyboard.TVSessionBeanObject.class);
		if (_so != null) {
			try {
				return ((Keyboard.TVSessionBeanObject)_so.servant).retrieveAllFromStub(stub);
			} finally {
				_servant_postinvoke(_so);
			}
		}
		org.omg.CORBA.portable.InputStream _in = null;
		try {
			org.omg.CORBA.portable.OutputStream _out = _request("retrieveAllFromStub", true);
			_ByteArray_write(_out, stub);
			_in = _invoke(_out);
			byte[] _zz = _ByteArray_read(_in);
			return _zz;
		} catch (org.omg.CORBA.portable.ApplicationException _ex) {
			org.omg.CORBA.portable.InputStream exIn = _ex.getInputStream();
			java.lang.String exId = _ex.getId();
			if (exId.equals("IDL:javax/ejb/EJBEx:1.0")) {
				exIn.read_string();
				throw (javax.ejb.EJBException)((org.omg.CORBA_2_3.portable.InputStream)exIn).read_value(javax.ejb.EJBException.class);
			}
			throw new java.rmi.UnexpectedException(exId);
		} catch (org.omg.CORBA.SystemException _ex) {
			throw javax.rmi.CORBA.Util.mapSystemException(_ex);
		} catch (org.omg.CORBA.portable.RemarshalException _ex) {
			return retrieveAllFromStub(stub);
		} finally {
			_releaseReply(_in);
		}
	}

	public void clearDB() throws java.rmi.RemoteException, javax.ejb.EJBException {
		org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("clearDB", Keyboard.TVSessionBeanObject.class);
		if (_so != null) {
			try {
				((Keyboard.TVSessionBeanObject)_so.servant).clearDB();
				return;
			} finally {
				_servant_postinvoke(_so);
			}
		}
		try {
			org.omg.CORBA.portable.OutputStream _out = _request("clearDB", true);
			_invoke(_out);
		} catch (org.omg.CORBA.portable.ApplicationException _ex) {
			org.omg.CORBA.portable.InputStream exIn = _ex.getInputStream();
			java.lang.String exId = _ex.getId();
			if (exId.equals("IDL:javax/ejb/EJBEx:1.0")) {
				exIn.read_string();
				throw (javax.ejb.EJBException)((org.omg.CORBA_2_3.portable.InputStream)exIn).read_value(javax.ejb.EJBException.class);
			}
			throw new java.rmi.UnexpectedException(exId);
		} catch (org.omg.CORBA.SystemException _ex) {
			throw javax.rmi.CORBA.Util.mapSystemException(_ex);
		} catch (org.omg.CORBA.portable.RemarshalException _ex) {
			clearDB();
		}
	}

	public void execute(byte[] command) throws java.rmi.RemoteException, javax.ejb.EJBException {
		org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("execute", Keyboard.TVSessionBeanObject.class);
		if (_so != null) {
			try {
				((Keyboard.TVSessionBeanObject)_so.servant).execute(command);
				return;
			} finally {
				_servant_postinvoke(_so);
			}
		}
		try {
			org.omg.CORBA.portable.OutputStream _out = _request("execute", true);
			_ByteArray_write(_out, command);
			_invoke(_out);
		} catch (org.omg.CORBA.portable.ApplicationException _ex) {
			org.omg.CORBA.portable.InputStream exIn = _ex.getInputStream();
			java.lang.String exId = _ex.getId();
			if (exId.equals("IDL:javax/ejb/EJBEx:1.0")) {
				exIn.read_string();
				throw (javax.ejb.EJBException)((org.omg.CORBA_2_3.portable.InputStream)exIn).read_value(javax.ejb.EJBException.class);
			}
			throw new java.rmi.UnexpectedException(exId);
		} catch (org.omg.CORBA.SystemException _ex) {
			throw javax.rmi.CORBA.Util.mapSystemException(_ex);
		} catch (org.omg.CORBA.portable.RemarshalException _ex) {
			execute(command);
		}
	}

	public long allocateIDs(int quantity) throws java.rmi.RemoteException, javax.ejb.EJBException {
		org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("allocateIDs", Keyboard.TVSessionBeanObject.class);
		if (_so != null) {
			try {
				return ((Keyboard.TVSessionBeanObject)_so.servant).allocateIDs(quantity);
			} finally {
				_servant_postinvoke(_so);
			}
		}
		org.omg.CORBA.portable.InputStream _in = null;
		try {
			org.omg.CORBA.portable.OutputStream _out = _request("allocateIDs", true);
			_out.write_long(quantity);
			_in = _invoke(_out);
			long _zz = _in.read_longlong();
			return _zz;
		} catch (org.omg.CORBA.portable.ApplicationException _ex) {
			org.omg.CORBA.portable.InputStream exIn = _ex.getInputStream();
			java.lang.String exId = _ex.getId();
			if (exId.equals("IDL:javax/ejb/EJBEx:1.0")) {
				exIn.read_string();
				throw (javax.ejb.EJBException)((org.omg.CORBA_2_3.portable.InputStream)exIn).read_value(javax.ejb.EJBException.class);
			}
			throw new java.rmi.UnexpectedException(exId);
		} catch (org.omg.CORBA.SystemException _ex) {
			throw javax.rmi.CORBA.Util.mapSystemException(_ex);
		} catch (org.omg.CORBA.portable.RemarshalException _ex) {
			return allocateIDs(quantity);
		} finally {
			_releaseReply(_in);
		}
	}
	static private byte[] _ByteArray_read(org.omg.CORBA.portable.InputStream _in)
	{
		int _zz = _in.read_long();
		if(_zz > 1000000) {
			throw new org.omg.CORBA.BAD_PARAM("ByteArray exceeded bound");
		}
		byte[]  _value = new byte[_zz];
		for(int _i = 0; _i < _zz; ++_i) {
			_value[_i] = _in.read_octet();
		}
		return _value;
	}
	static private void _ByteArray_write(org.omg.CORBA.portable.OutputStream _out, byte[] _value)
	{
		if(_value.length > 1000000) {
			throw new org.omg.CORBA.BAD_PARAM("ByteArray exceeded bound");
		}
		_out.write_long(_value.length);
		for(int _i = 0; _i < _value.length; ++_i) {
			_out.write_octet(_value[_i]);
		}
	}
}
