/* Secant Object Implementation for Assoc_15729533 (safe).
 * generated by emit_jbo(Oct 25 2000) on 12/08/00 at 11:05:20 AM
 */
package Keyboard;
import secant.util.Money;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.math.*;
import secant.portable.persistence.*;



// begin_safe_imports
// end_safe_imports

public class Assoc_15729533
	// begin_safe_additionalInterfaces
	// end_safe_additionalInterfaces
{
	private long Keyboard_TVPCakboid;
	private long Keyboard_TVPCbkboid;
	private int obj1;
	private int obj2;
	private DirtyBits _dirtyBits_;
	// begin_safe_members
	// end_safe_members

	public Assoc_15729533()
	{
		PersistenceService _ps = PersistenceService.getInstance();
		_dirtyBits_ = _ps.createDirtyBits(4);
		// begin_safe_constructNoArgs
		// end_safe_constructNoArgs
	}

	// factory method(s)
	public static Assoc_15729533 createAssoc_15729533(long Keyboard_TVPCakboid, long Keyboard_TVPCbkboid, String _loc) throws PersistenceException
	{
		Assoc_15729533 _obj = new Assoc_15729533();
		_obj.setKeyboard_TVPCakboid(Keyboard_TVPCakboid);
		_obj.setKeyboard_TVPCbkboid(Keyboard_TVPCbkboid);
		PersistenceService.getInstance().activateNew(_obj, _loc);
		// begin_safe_factory
		// end_safe_factory
		return _obj;
	}

	public static Assoc_15729533 createAssoc_15729533(long Keyboard_TVPCakboid, long Keyboard_TVPCbkboid) throws PersistenceException
	{
		return createAssoc_15729533(Keyboard_TVPCakboid, Keyboard_TVPCbkboid, null);
	}

	// begin_safe_constructors
	// end_safe_constructors

	// attribute accessor methods


	// begin_safe_getKeyboard_TVPCakboid_javadoc_comment
	// end_safe_getKeyboard_TVPCakboid_javadoc_comment
	public long getKeyboard_TVPCakboid()
	{
		// begin_safe_getKeyboard_TVPCakboid
		// end_safe_getKeyboard_TVPCakboid
		return Keyboard_TVPCakboid;
	}

	// begin_safe_setKeyboard_TVPCakboid_javadoc_comment
	// end_safe_setKeyboard_TVPCakboid_javadoc_comment
	protected void setKeyboard_TVPCakboid(long _zz)
	{
		_dirtyBits_.setDirty(this, 1);
		// begin_safe_setKeyboard_TVPCakboid
		Keyboard_TVPCakboid = _zz;
		// end_safe_setKeyboard_TVPCakboid
	}

	// begin_safe_getKeyboard_TVPCbkboid_javadoc_comment
	// end_safe_getKeyboard_TVPCbkboid_javadoc_comment
	public long getKeyboard_TVPCbkboid()
	{
		// begin_safe_getKeyboard_TVPCbkboid
		// end_safe_getKeyboard_TVPCbkboid
		return Keyboard_TVPCbkboid;
	}

	// begin_safe_setKeyboard_TVPCbkboid_javadoc_comment
	// end_safe_setKeyboard_TVPCbkboid_javadoc_comment
	protected void setKeyboard_TVPCbkboid(long _zz)
	{
		_dirtyBits_.setDirty(this, 2);
		// begin_safe_setKeyboard_TVPCbkboid
		Keyboard_TVPCbkboid = _zz;
		// end_safe_setKeyboard_TVPCbkboid
	}

	// begin_safe_getObj1_javadoc_comment
	// end_safe_getObj1_javadoc_comment
	public int getObj1()
	{
		// begin_safe_getObj1
		// end_safe_getObj1
		return obj1;
	}

	// begin_safe_setObj1_javadoc_comment
	// end_safe_setObj1_javadoc_comment
	public void setObj1(int _zz)
	{
		// begin_safe_setObj1
		obj1 = _zz;
		// end_safe_setObj1
	}

	// begin_safe_getObj2_javadoc_comment
	// end_safe_getObj2_javadoc_comment
	public int getObj2()
	{
		// begin_safe_getObj2
		// end_safe_getObj2
		return obj2;
	}

	// begin_safe_setObj2_javadoc_comment
	// end_safe_setObj2_javadoc_comment
	public void setObj2(int _zz)
	{
		// begin_safe_setObj2
		obj2 = _zz;
		// end_safe_setObj2
	}

	// operations

	// begin_safe_additional_methods
	// end_safe_additional_methods
}

// begin_safe_other
// end_safe_other


/*    -- begin 
// begin_safe_ORPHANED_SAFE_BLOCKS
// end_safe_ORPHANED_SAFE_BLOCKS
*/ // -- end 
