/* Secant Object Implementation for TVPCa (safe).
 * generated by emit_jbo(Dec 21 2000) on 05/03/01 at 10:28:25 AM
 */
package Keyboard;
import secant.util.Money;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.math.*;
import secant.portable.persistence.*;



// begin_safe_imports
import Keyboard.clientBusinessObjects.*;
import java.io.*;
// end_safe_imports

public class TVPCa extends Keyboard.TVPComponent
	// begin_safe_additionalInterfaces
	// end_safe_additionalInterfaces
{
	private long Fk_9044186;
	private AssociationReference husband;
	private AssociationReference brothers;
	private DirtyBits _dirtyBits_;
	// begin_safe_members
	// end_safe_members

	public TVPCa()
	{
		super();
		PersistenceService _ps = PersistenceService.getInstance();
		_dirtyBits_ = _ps.createDirtyBits(3);
		husband = _ps.createAssociationReference(this, "husband");
		brothers = _ps.createAssociationReference(this, "brothers");
		// begin_safe_constructNoArgs
		// end_safe_constructNoArgs
	}

	// factory method(s)
	public static TVPCa createTVPCa(long kboid, String _loc) throws PersistenceException
	{
		TVPCa _obj = new TVPCa();
		_obj.setKboid(kboid);
		PersistenceService.getInstance().activateNew(_obj, _loc);
		// begin_safe_factory
		// end_safe_factory
		return _obj;
	}

	public static TVPCa createTVPCa(long kboid) throws PersistenceException
	{
		return createTVPCa(kboid, null);
	}

	// begin_safe_constructors
	// end_safe_constructors

	// attribute accessor methods


	// begin_safe_getFk_9044186_javadoc_comment
	// end_safe_getFk_9044186_javadoc_comment
	protected long getFk_9044186()
	{
		// begin_safe_getFk_9044186
		// end_safe_getFk_9044186
		return Fk_9044186;
	}

	// begin_safe_setFk_9044186_javadoc_comment
	// end_safe_setFk_9044186_javadoc_comment
	protected void setFk_9044186(long _zz)
	{
		_dirtyBits_.setDirty(this, 1);
		// begin_safe_setFk_9044186
		Fk_9044186 = _zz;
		// end_safe_setFk_9044186
	}

	// begin_safe_getHusband_javadoc_comment
	// end_safe_getHusband_javadoc_comment
	public Keyboard.TVPCb getHusband() throws PersistenceException
	{
		// begin_safe_getHusband
		// end_safe_getHusband
		return (Keyboard.TVPCb)husband.get();
	}

	// begin_safe_setHusband_javadoc_comment
	// end_safe_setHusband_javadoc_comment
	public void setHusband(Keyboard.TVPCb _obj) throws PersistenceException
	{
		// begin_safe_setHusband
                try
                {
                  if( _obj == null )
                  {
                    return;
                  }
                  Visitable old = getHusband();
                  if( old != null && ! old.equals( _obj ) )
                  {
                    husband.disassociate( old );
                  }
                  husband.associate( _obj );
                }
                catch( PersistenceException exc )
                {
                  exc.printStackTrace();
                  throw exc;
                }
		// end_safe_setHusband
	}

	// begin_safe_getBrothers_javadoc_comment
	// end_safe_getBrothers_javadoc_comment
	public java.util.LinkedList getBrothers() throws PersistenceException
	{
		// begin_safe_getBrothers
		// end_safe_getBrothers
		return (java.util.LinkedList)brothers.get();
	}

	// begin_safe_addBrother_javadoc_comment
	// end_safe_addBrother_javadoc_comment
	public void addBrother(Keyboard.TVPCb _obj) throws PersistenceException
	{
		// begin_safe_addBrother
		brothers.associate(_obj);
		// end_safe_addBrother
	}

	// begin_safe_removeBrother_javadoc_comment
	// end_safe_removeBrother_javadoc_comment
	public void removeBrother(Keyboard.TVPCb _obj) throws PersistenceException
	{
		// begin_safe_removeBrother
		brothers.disassociate(_obj);
		// end_safe_removeBrother
	}

	// operations

	// begin_safe_additional_methods

  public Visitable accept( Visitor aVisitor )
  {
    return aVisitor.visit( (TVPCa) this ).postAccept( aVisitor );
  }

  public Visitable postAccept( Visitor aVisitor )
  {
    super.postAccept(aVisitor);
    aVisitor.postVisit( (TVPCa) this );
    return this;
  }

  public String otherClassName()
  {
    return "TVCa";
  }

	// end_safe_additional_methods
}

// begin_safe_other
// end_safe_other


/*    -- begin 
// begin_safe_ORPHANED_SAFE_BLOCKS
// begin_safe_addToOneCb
		toOneCb.associate(_obj);
// end_safe_addToOneCb
// begin_safe_toOneCb
		toOneCb.associate(_obj);
// end_safe_toOneCb
// begin_safe_set
		toOneCb.associate(_obj);
// end_safe_set
// begin_safe_}
		toOneCb.associate(_obj);
// end_safe_}
// begin_safe_toOneCb
		toOneCb.associate(_obj);
// end_safe_toOneCb
// begin_safe_addHusband
		husband.associate(_obj);
// end_safe_addHusband
// begin_safe_addBrothers
		brothers.associate(_obj);
// end_safe_addBrothers
// begin_safe_addSister
		brothers.associate(_obj);
// end_safe_addSister
// begin_safe_removeSister
		brothers.disassociate(_obj);
// end_safe_removeSister
// begin_safe_setFk_2883928
		Fk_2883928 = _zz;
// end_safe_setFk_2883928
// begin_safe_addToManyCb
		toManyCbs.associate(_obj);
// end_safe_addToManyCb
// begin_safe_removeToManyCb
		toManyCbs.disassociate(_obj);
// end_safe_removeToManyCb
// begin_safe_setToOneCb

                try
                {
                  if( _obj == null )
                  {
                    return;
                  }
                  Visitable old = getToOneCb();
                  if( old != null && ! old.equals( _obj ) )
                  {
                    toOneCb.disassociate( old );
                  }
                  toOneCb.associate( _obj );
                }
                catch( PersistenceException exc )
                {
                  exc.printStackTrace();
                  throw exc;
                }

// end_safe_setToOneCb
// end_safe_ORPHANED_SAFE_BLOCKS
*/ // -- end 
