/* Secant Object Implementation for TVPComponent (safe).
 * generated by emit_jbo(Dec 21 2000) on 02/23/01 at 03:14:44 PM
 */
package Keyboard;
import secant.util.Money;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.math.*;
import secant.portable.persistence.*;



// begin_safe_imports
import Keyboard.clientBusinessObjects.*;
import java.io.*;
// end_safe_imports

public class TVPComponent
	// begin_safe_additionalInterfaces
 implements Visitable
	// end_safe_additionalInterfaces
{
	private long kboid;
	private boolean newlyCreated;
	private boolean modified;
	private String name = "";
	private String alias = "";
	private int updateCounter;
	private long Fk_14286961;
	private AssociationReference parent;
	private DirtyBits _dirtyBits_;
	// begin_safe_members
	// end_safe_members

	public TVPComponent()
	{
		PersistenceService _ps = PersistenceService.getInstance();
		_dirtyBits_ = _ps.createDirtyBits(8);
		parent = _ps.createAssociationReference(this, "parent");
		// begin_safe_constructNoArgs
		// end_safe_constructNoArgs
	}

	// factory method(s)
	public static TVPComponent createTVPComponent(long kboid, String _loc) throws PersistenceException
	{
		TVPComponent _obj = new TVPComponent();
		_obj.setKboid(kboid);
		PersistenceService.getInstance().activateNew(_obj, _loc);
		// begin_safe_factory
		// end_safe_factory
		return _obj;
	}

	public static TVPComponent createTVPComponent(long kboid) throws PersistenceException
	{
		return createTVPComponent(kboid, null);
	}

	// begin_safe_constructors
	// end_safe_constructors

	// attribute accessor methods


	// begin_safe_getKboid_javadoc_comment
	// end_safe_getKboid_javadoc_comment
	public long getKboid()
	{
		// begin_safe_getKboid
		// end_safe_getKboid
		return kboid;
	}

	// begin_safe_setKboid_javadoc_comment
	// end_safe_setKboid_javadoc_comment
	protected void setKboid(long _zz)
	{
		_dirtyBits_.setDirty(this, 1);
		// begin_safe_setKboid
		kboid = _zz;
		// end_safe_setKboid
	}

	// begin_safe_getNewlyCreated_javadoc_comment
	// end_safe_getNewlyCreated_javadoc_comment
	public boolean getNewlyCreated()
	{
		// begin_safe_getNewlyCreated
		// end_safe_getNewlyCreated
		return newlyCreated;
	}

	// begin_safe_setNewlyCreated_javadoc_comment
	// end_safe_setNewlyCreated_javadoc_comment
	public void setNewlyCreated(boolean _zz)
	{
		_dirtyBits_.setDirty(this, 2);
		// begin_safe_setNewlyCreated
		newlyCreated = _zz;
		// end_safe_setNewlyCreated
	}

	// begin_safe_getModified_javadoc_comment
	// end_safe_getModified_javadoc_comment
	public boolean getModified()
	{
		// begin_safe_getModified
		// end_safe_getModified
		return modified;
	}

	// begin_safe_setModified_javadoc_comment
	// end_safe_setModified_javadoc_comment
	public void setModified(boolean _zz)
	{
		_dirtyBits_.setDirty(this, 3);
		// begin_safe_setModified
		modified = _zz;
		// end_safe_setModified
	}

	// begin_safe_getName_javadoc_comment
	// end_safe_getName_javadoc_comment
	public String getName()
	{
		// begin_safe_getName
		// end_safe_getName
		return name;
	}

	// begin_safe_setName_javadoc_comment
	// end_safe_setName_javadoc_comment
	public void setName(String _zz)
	{
		_dirtyBits_.setDirty(this, 4);
		if (_zz != null)
			PersistenceUtil.checkBounds("name", _zz.length(), 64);
		// begin_safe_setName
		name = _zz;
		// end_safe_setName
	}

	// begin_safe_getAlias_javadoc_comment
	// end_safe_getAlias_javadoc_comment
	public String getAlias()
	{
		// begin_safe_getAlias
		// end_safe_getAlias
		return alias;
	}

	// begin_safe_setAlias_javadoc_comment
	// end_safe_setAlias_javadoc_comment
	public void setAlias(String _zz)
	{
		_dirtyBits_.setDirty(this, 5);
		if (_zz != null)
			PersistenceUtil.checkBounds("alias", _zz.length(), 64);
		// begin_safe_setAlias
		alias = _zz;
		// end_safe_setAlias
	}

	// begin_safe_getUpdateCounter_javadoc_comment
	// end_safe_getUpdateCounter_javadoc_comment
	public int getUpdateCounter()
	{
		// begin_safe_getUpdateCounter
		// end_safe_getUpdateCounter
		return updateCounter;
	}

	// begin_safe_setUpdateCounter_javadoc_comment
	// end_safe_setUpdateCounter_javadoc_comment
	public void setUpdateCounter(int _zz)
	{
		_dirtyBits_.setDirty(this, 6);
		// begin_safe_setUpdateCounter
		updateCounter = _zz;
		// end_safe_setUpdateCounter
	}

	// begin_safe_getFk_14286961_javadoc_comment
	// end_safe_getFk_14286961_javadoc_comment
	protected long getFk_14286961()
	{
		// begin_safe_getFk_14286961
		// end_safe_getFk_14286961
		return Fk_14286961;
	}

	// begin_safe_setFk_14286961_javadoc_comment
	// end_safe_setFk_14286961_javadoc_comment
	protected void setFk_14286961(long _zz)
	{
		_dirtyBits_.setDirty(this, 7);
		// begin_safe_setFk_14286961
		Fk_14286961 = _zz;
		// end_safe_setFk_14286961
	}

	// begin_safe_getParent_javadoc_comment
	// end_safe_getParent_javadoc_comment
	public Keyboard.TVPComposite getParent() throws PersistenceException
	{
		// begin_safe_getParent
		// end_safe_getParent
		return (Keyboard.TVPComposite)parent.get();
	}

	// begin_safe_setParent_javadoc_comment
	// end_safe_setParent_javadoc_comment
	public void setParent(Keyboard.TVPComposite _obj) throws PersistenceException
	{
		// begin_safe_setParent

                try
                {
                  if( _obj == null )
                  {
                    return;
                  }
                  Visitable old = getParent();
                  if( old != null && ! old.equals( _obj ) )
                  {
                    parent.disassociate( old );
                  }
                  parent.associate( _obj );
                }
                catch( PersistenceException exc )
                {
                  exc.printStackTrace();
                  throw exc;
                }



                parent.disassociate( this.getParent() );
		parent.associate(_obj);
		// end_safe_setParent
	}

	// operations


	// begin_safe_xsetKboid_javadoc_comment
	// end_safe_xsetKboid_javadoc_comment
	public void xsetKboid(long theKboid)
	// begin_safe_xsetKboid_throws
	// end_safe_xsetKboid_throws

	{
	// begin_safe_xsetKboid

          setKboid( theKboid );

	// end_safe_xsetKboid
	}


	// begin_safe_isNewlyCreated_javadoc_comment
	// end_safe_isNewlyCreated_javadoc_comment
	public boolean isNewlyCreated()
	// begin_safe_isNewlyCreated_throws
	// end_safe_isNewlyCreated_throws

	{
	// begin_safe_isNewlyCreated
		return getNewlyCreated();
	// end_safe_isNewlyCreated
	}


	// begin_safe_isModified_javadoc_comment
	// end_safe_isModified_javadoc_comment
	public boolean isModified()
	// begin_safe_isModified_throws
	// end_safe_isModified_throws

	{
	// begin_safe_isModified
		return getModified();
	// end_safe_isModified
	}

	// begin_safe_additional_methods

  public Visitable accept( Visitor aVisitor )
  {
    return aVisitor.visit( (TVPComponent) this ).postAccept( aVisitor );
  }

  public Visitable postAccept( Visitor aVisitor )
  {
    aVisitor.postVisit( (TVPComponent) this );
    return this;
  }

  public Object clone()
  {
    try
    {
      return super.clone();
    }
    catch( CloneNotSupportedException e )
    {
      // Cannot happen -- all TVPComponents support  cloning
      throw new InternalError( e.toString() );
    }
  }

  public boolean equals( Object another )
  {
    return getKboid() == ((Visitable)another).getKboid();
  }

  public int compareTo( Object another )
  {
    return (new Long( getKboid() )).compareTo( new Long( ((Visitable)another).getKboid() ));
  }

  public int hashCode()
  {
    return (int) kboid;
  }

  public String toString()
  {
    return super.toString() + " -- " + name + getKboid();
  }

  public String otherClassName()
  {
    return "TVComponent";
  }

  public Stub toStub()
  {
    return new Stub( getKboid(), getClass().getName() );
  }

  public void incrementUpdateCounter()
  {
    setUpdateCounter( getUpdateCounter() + 1 );
  }

  public void save() throws Exception
  {
  }

  public void setAssociationsCoordinator( AssociationsCoordinator _associationsCoordinator )
  {
  }

  public AssociationsCoordinator getAssociationsCoordinator()
  {
    return null;
  }

  public boolean isStub()
  {
    return false;
  }

  public StubInterface yourself()
  {
    return (StubInterface) this;
  }

  public Visitable refresh() throws javax.transaction.SystemException, java.lang.Exception, java.rmi.RemoteException
  {
    return this;
  }

	// end_safe_additional_methods
}

// begin_safe_other
// end_safe_other


/*    -- begin
// begin_safe_ORPHANED_SAFE_BLOCKS
// begin_safe_setParent
		parent.associate(_obj);
// end_safe_setParent
// begin_safe_addParent
		parent.associate(_obj);
// end_safe_addParent
// begin_safe_removeParent
		parent.disassociate(null);
// end_safe_removeParent
// end_safe_ORPHANED_SAFE_BLOCKS
*/ // -- end
