/*
 * generated by emit_jco(Dec 21 2000) on 04/23/01 at 02:28:57 PM
 *
 * Remote interface implementation for session bean Keyboard.TVSessionBean
 */
package Keyboard;

import secant.ejb.EJBContext;
import java.rmi.RemoteException;
import javax.ejb.EJBHome;
import javax.ejb.EJBObject;
import javax.ejb.RemoveException;


// begin_safe_additional_imports
// end_safe_additional_imports

public class TVSessionBeanObject_TVSessionBean extends secant.ejb.SessionBeanRemoteImpl implements Keyboard.TVSessionBeanObject
// begin_safe_additional_interfaces
// end_safe_additional_interfaces
{
	Keyboard.TVSessionBean _target = null;

	// ctor
	public TVSessionBeanObject_TVSessionBean() throws java.rmi.RemoteException
	{
		// begin_safe__ctor_
		// end_safe__ctor_
	}

	public void _setContext(secant.ejb.EJBContext ctx)
	{
		super._setContext(ctx);
		_target = ((ctx != null)?(Keyboard.TVSessionBean)ctx.getBean():null);
	}

	public javax.ejb.EnterpriseBean _getTarget()
	{
		return _target;
	}

	//
	// ejbClass methods
	//
	public String greeting() throws javax.ejb.EJBException, java.rmi.RemoteException
	{
		// begin_safe_greeting
		// end_safe_greeting

		String _result;
		secant.ejb.policy.RequiresNew _txpolicy = null;
		try {
            secant.security.Security.provider.setPropagation(secant.security.SecurityService.SP_received);
			_txpolicy = new secant.ejb.policy.RequiresNew("Keyboard.TVSessionBeanObject.greeting", _getService());
			_txParticipate();
			_result = 
				_target.greeting();
		}
		catch (Throwable _t) {
			_reportException("greeting",_t);
			_handleException(_t, _txpolicy);
			if (_txpolicy!=null)_txpolicy.rollback();
			if (_t instanceof javax.ejb.EJBException)
			   throw (javax.ejb.EJBException)_t;
			throw new javax.ejb.EJBException("-- greeting error: "+_t.getMessage()+" -- "+_t.toString());
		}
		finally {
			if (_txpolicy != null)
				_txpolicy.cleanup();
		}
		return _result;
	}

	public void storeAll(byte[] objectGraph) throws javax.ejb.EJBException, java.rmi.RemoteException
	{
		// begin_safe_storeAll
		// end_safe_storeAll

		secant.ejb.policy.RequiresNew _txpolicy = null;
		try {
            secant.security.Security.provider.setPropagation(secant.security.SecurityService.SP_received);
			_txpolicy = new secant.ejb.policy.RequiresNew("Keyboard.TVSessionBeanObject.storeAll", _getService());
			_txParticipate();
			_target.storeAll(objectGraph);
		}
		catch (Throwable _t) {
			_reportException("storeAll",_t);
			_handleException(_t, _txpolicy);
			if (_txpolicy!=null)_txpolicy.rollback();
			if (_t instanceof javax.ejb.EJBException)
			   throw (javax.ejb.EJBException)_t;
			throw new javax.ejb.EJBException("-- storeAll error: "+_t.getMessage()+" -- "+_t.toString());
		}
		finally {
			if (_txpolicy != null)
				_txpolicy.cleanup();
		}
	}

	public void testCreateOne() throws javax.ejb.EJBException, java.rmi.RemoteException
	{
		// begin_safe_testCreateOne
		// end_safe_testCreateOne

		secant.ejb.policy.RequiresNew _txpolicy = null;
		try {
            secant.security.Security.provider.setPropagation(secant.security.SecurityService.SP_received);
			_txpolicy = new secant.ejb.policy.RequiresNew("Keyboard.TVSessionBeanObject.testCreateOne", _getService());
			_txParticipate();
			_target.testCreateOne();
		}
		catch (Throwable _t) {
			_reportException("testCreateOne",_t);
			_handleException(_t, _txpolicy);
			if (_txpolicy!=null)_txpolicy.rollback();
			if (_t instanceof javax.ejb.EJBException)
			   throw (javax.ejb.EJBException)_t;
			throw new javax.ejb.EJBException("-- testCreateOne error: "+_t.getMessage()+" -- "+_t.toString());
		}
		finally {
			if (_txpolicy != null)
				_txpolicy.cleanup();
		}
	}

	public void testCreateAll() throws javax.ejb.EJBException, java.rmi.RemoteException
	{
		// begin_safe_testCreateAll
		// end_safe_testCreateAll

		secant.ejb.policy.RequiresNew _txpolicy = null;
		try {
            secant.security.Security.provider.setPropagation(secant.security.SecurityService.SP_received);
			_txpolicy = new secant.ejb.policy.RequiresNew("Keyboard.TVSessionBeanObject.testCreateAll", _getService());
			_txParticipate();
			_target.testCreateAll();
		}
		catch (Throwable _t) {
			_reportException("testCreateAll",_t);
			_handleException(_t, _txpolicy);
			if (_txpolicy!=null)_txpolicy.rollback();
			if (_t instanceof javax.ejb.EJBException)
			   throw (javax.ejb.EJBException)_t;
			throw new javax.ejb.EJBException("-- testCreateAll error: "+_t.getMessage()+" -- "+_t.toString());
		}
		finally {
			if (_txpolicy != null)
				_txpolicy.cleanup();
		}
	}

	public byte[] retrieveAll(long seedID, String seedClass) throws javax.ejb.EJBException, java.rmi.RemoteException
	{
		// begin_safe_retrieveAll
		// end_safe_retrieveAll

		byte[] _result;
		secant.ejb.policy.RequiresNew _txpolicy = null;
		try {
            secant.security.Security.provider.setPropagation(secant.security.SecurityService.SP_received);
			_txpolicy = new secant.ejb.policy.RequiresNew("Keyboard.TVSessionBeanObject.retrieveAll", _getService());
			_txParticipate();
			_result = 
				_target.retrieveAll(seedID, seedClass);
		}
		catch (Throwable _t) {
			_reportException("retrieveAll",_t);
			_handleException(_t, _txpolicy);
			if (_txpolicy!=null)_txpolicy.rollback();
			if (_t instanceof javax.ejb.EJBException)
			   throw (javax.ejb.EJBException)_t;
			throw new javax.ejb.EJBException("-- retrieveAll error: "+_t.getMessage()+" -- "+_t.toString());
		}
		finally {
			if (_txpolicy != null)
				_txpolicy.cleanup();
		}
		return _result;
	}

	public byte[] retrieveAllFromStub(byte[] stub) throws javax.ejb.EJBException, java.rmi.RemoteException
	{
		// begin_safe_retrieveAllFromStub
		// end_safe_retrieveAllFromStub

		byte[] _result;
		secant.ejb.policy.RequiresNew _txpolicy = null;
		try {
            secant.security.Security.provider.setPropagation(secant.security.SecurityService.SP_received);
			_txpolicy = new secant.ejb.policy.RequiresNew("Keyboard.TVSessionBeanObject.retrieveAllFromStub", _getService());
			_txParticipate();
			_result = 
				_target.retrieveAllFromStub(stub);
		}
		catch (Throwable _t) {
			_reportException("retrieveAllFromStub",_t);
			_handleException(_t, _txpolicy);
			if (_txpolicy!=null)_txpolicy.rollback();
			if (_t instanceof javax.ejb.EJBException)
			   throw (javax.ejb.EJBException)_t;
			throw new javax.ejb.EJBException("-- retrieveAllFromStub error: "+_t.getMessage()+" -- "+_t.toString());
		}
		finally {
			if (_txpolicy != null)
				_txpolicy.cleanup();
		}
		return _result;
	}

	public void clearDB() throws javax.ejb.EJBException, java.rmi.RemoteException
	{
		// begin_safe_clearDB
		// end_safe_clearDB

		secant.ejb.policy.RequiresNew _txpolicy = null;
		try {
            secant.security.Security.provider.setPropagation(secant.security.SecurityService.SP_received);
			_txpolicy = new secant.ejb.policy.RequiresNew("Keyboard.TVSessionBeanObject.clearDB", _getService());
			_txParticipate();
			_target.clearDB();
		}
		catch (Throwable _t) {
			_reportException("clearDB",_t);
			_handleException(_t, _txpolicy);
			if (_txpolicy!=null)_txpolicy.rollback();
			if (_t instanceof javax.ejb.EJBException)
			   throw (javax.ejb.EJBException)_t;
			throw new javax.ejb.EJBException("-- clearDB error: "+_t.getMessage()+" -- "+_t.toString());
		}
		finally {
			if (_txpolicy != null)
				_txpolicy.cleanup();
		}
	}

	public void execute(byte[] command) throws javax.ejb.EJBException, java.rmi.RemoteException
	{
		// begin_safe_execute
		// end_safe_execute

		secant.ejb.policy.RequiresNew _txpolicy = null;
		try {
            secant.security.Security.provider.setPropagation(secant.security.SecurityService.SP_received);
			_txpolicy = new secant.ejb.policy.RequiresNew("Keyboard.TVSessionBeanObject.execute", _getService());
			_txParticipate();
			_target.execute(command);
		}
		catch (Throwable _t) {
			_reportException("execute",_t);
			_handleException(_t, _txpolicy);
			if (_txpolicy!=null)_txpolicy.rollback();
			if (_t instanceof javax.ejb.EJBException)
			   throw (javax.ejb.EJBException)_t;
			throw new javax.ejb.EJBException("-- execute error: "+_t.getMessage()+" -- "+_t.toString());
		}
		finally {
			if (_txpolicy != null)
				_txpolicy.cleanup();
		}
	}

	public long allocateIDs(int quantity) throws javax.ejb.EJBException, java.rmi.RemoteException
	{
		// begin_safe_allocateIDs
		// end_safe_allocateIDs

		long _result;
		secant.ejb.policy.RequiresNew _txpolicy = null;
		try {
            secant.security.Security.provider.setPropagation(secant.security.SecurityService.SP_received);
			_txpolicy = new secant.ejb.policy.RequiresNew("Keyboard.TVSessionBeanObject.allocateIDs", _getService());
			_txParticipate();
			_result = 
				_target.allocateIDs(quantity);
		}
		catch (Throwable _t) {
			_reportException("allocateIDs",_t);
			_handleException(_t, _txpolicy);
			if (_txpolicy!=null)_txpolicy.rollback();
			if (_t instanceof javax.ejb.EJBException)
			   throw (javax.ejb.EJBException)_t;
			throw new javax.ejb.EJBException("-- allocateIDs error: "+_t.getMessage()+" -- "+_t.toString());
		}
		finally {
			if (_txpolicy != null)
				_txpolicy.cleanup();
		}
		return _result;
	}

	// begin_safe_additional_methods
	// end_safe_additional_methods
}

/*    -- begin 
// begin_safe_orphaned user code
// end_safe_orphaned user code
*/ // -- end 
