/* generated by emit_jrmi(Aug 16 2000) on 11/08/00 at 11:02:22 AM from Keyboard.odl
*/

package Keyboard;

public interface TVSessionBeanHome extends java.rmi.Remote, javax.ejb.EJBHome {
	public Keyboard.TVSessionBeanObject create() throws java.rmi.RemoteException, javax.ejb.CreateException;
}
