/* generated by emit_jrmi(Dec 21 2000) on 04/19/01 at 09:56:08 AM from Keyboard.odl
*/

package Keyboard;

public interface TVSessionBeanObject extends java.rmi.Remote, javax.ejb.EJBObject {
	public String greeting() throws java.rmi.RemoteException, javax.ejb.EJBException;
	public void storeAll(byte[] objectGraph) throws java.rmi.RemoteException, javax.ejb.EJBException;
	public void testCreateOne() throws java.rmi.RemoteException, javax.ejb.EJBException;
	public void testCreateAll() throws java.rmi.RemoteException, javax.ejb.EJBException;
	public byte[] retrieveAll(long seedID, String seedClass) throws java.rmi.RemoteException, javax.ejb.EJBException;
	public byte[] retrieveAllFromStub(byte[] stub) throws java.rmi.RemoteException, javax.ejb.EJBException;
	public void clearDB() throws java.rmi.RemoteException, javax.ejb.EJBException;
	public void execute(byte[] command) throws java.rmi.RemoteException, javax.ejb.EJBException;
	public long allocateIDs(int quantity) throws java.rmi.RemoteException, javax.ejb.EJBException;
}
