/* Generated by Together */

package model.test.client;

public class Composite extends Component 
{
    /**
     * @bidirectional <{model.test.client.Component#parent}>
     * @supplierRole children
     * @supplierCardinality 0..*
     * @clientRole parent
     * @clientCardinality 0..1 
     */
    private Component children;
}
