/* Generated by Together */

package model.test.client;

import model.PersistenceAdapter;

public class Component extends PersistenceAdapter 
{
    public String getName(){
            return name;
        }

    public void setName(String name){
            this.name = name;
        }

    public int getAge(){
            return age;
        }

    public void setAge(int age){
            this.age = age;
        }

    public String getAlias(){
            return alias;
        }

    public void setAlias(String alias){
            this.alias = alias;
        }

    /**
     * @labelDirection forward
     * @directed
     * @supplierRole bestFriend
     * @supplierCardinality 0..1 
     */
    /*#Component smartClient;*/

    /**
     * @labelDirection forward
     * @supplierCardinality 0..*
     * @supplierRole playmaates
     * @directed 
     */
    /*#Component playmates;*/
    private String alias;
    private int age;

    /**
     * @bidirectional 
     */
    private Composite parent;
    private String name;
}
