/* Generated by Together */

package model.test.client;

public class Female extends Component 
{
    /**
     * @bidirectional 
     */
    private Male brothers;

    /**
     * @bidirectional 
     */
    private Male husband;
}
