/* Generated by Together */

package model.test.client;

public class Male extends Component 
{
    /**
     * @supplierRole wife
     * @clientRole husband
     * @supplierCardinality 1
     * @clientCardinality 1
     * @bidirectional <{model.test.client.Female#husband}>*/
    private Female wife;

    /**
     * @supplierRole sisters
     * @clientRole brothers
     * @supplierCardinality 0..*
     * @clientCardinality 0..*
     * @bidirectional <{model.test.client.Female#brothers}>*/
    private Female sisters;
}
