/* Generated by Together */

package model.test.client;

public class Composite extends Component 
{
  public Persistable postAccept( Visitor aVisitor )
  {
    super.postAccept(aVisitor);
    aVisitor.postVisit( (Composite) this );
    return this;
  }
    public Collection getChildren()
    { return this.children.getAll(); }

    public void addChild(Component zzz )
    { this.children.add(zzz); }

    public void removeChild(Component zzz )
    { this.children.remove(zzz); }

    private ToMany children = new OneToMany(this, "children", "Component", "parent");
}
