/* Generated by Together */

package model.test.client;

public class Female extends Component 
{
  public Persistable postAccept( Visitor aVisitor )
  {
    super.postAccept(aVisitor);
    aVisitor.postVisit( (Female) this );
    return this;
  }

    public Male getHusband()
    { return (Male)this.husband.get(); }

    public void setHusband(Male zzz )
    { this.husband.set(zzz); }

    public Collection getBrothers()
    { return this.brothers.getAll(); }

    public void addBrother(Male zzz )
    { this.brothers.add(zzz); }

    public void removeBrother(Male zzz )
    { this.brothers.remove(zzz); }

    /**
     * @clientCardinality 0..*
     * @clientRole sisters
     * @supplierCardinality 0..*
     * @supplierRole brothers
     * @associates <{Male}>
     * @undirected*/
    private ToMany brothers = new ManyToMany(this, "brothers", "Male", "sisters");

    /**
     * @clientCardinality 1
     * @clientRole wife
     * @supplierCardinality 1
     * @supplierRole husband
     * @associates <{Male}>
     * @undirected*/
    private ToOne husband = new OneToOne(this, "husband", "Male", "wife");
}
