/* Generated by Together */

package model.test.client;

public class Male extends Component 
{
  public Persistable postAccept( Visitor aVisitor )
  {
    super.postAccept(aVisitor);
    aVisitor.postVisit( (Male) this );
    return this;
  }

    public Female getWife()
    { return (Female)this.wife.get(); }

    public void setWife(Female zzz )
    { this.wife.set(zzz); }

    public Collection getSisters()
    { return this.sisters.getAll(); }

    public void addSister(Female zzz )
    { this.sisters.add(zzz); }

    public void removeSister(Female zzz )
    { this.sisters.remove(zzz); }

    private ToOne wife = new OneToOne(this, "wife", "Female", "husband");
    private ToMany sisters = new ManyToMany(this, "sisters", "Female", "brothers");
}
