/* Generated by Together */

package com.togethersoft.modules.smartClient;

public interface Cardinality
{
	public static String NONE = "none";
    public static String ONE = "one";
    public static String MANY = "many";
}
