/* Generated by Together */

package com.togethersoft.modules.smartClient;

import com.togethersoft.openapi.rwi.RwiLink;
import com.togethersoft.openapi.rwi.RwiProperty;
import com.togethersoft.openapi.rwi.RwiNode;

public class ClientEnd extends AssociationEnd 
{
	ClientEnd( Association theAssociation )
    {
    	super( theAssociation );
    }

	AssociationEnd getOtherEnd()
    {
    	return getAssociation().getSupplierEnd();
    }

	public String toString()
    {
    	return " <<Client>> " + super.toString();
    }

	void extractModelInfo( RwiLink link )
    {
		setRole( link.getProperty( Association.UserDefinedPropertyName.CLIENT_ROLE ) );
		setRawCardinality( link.getProperty( Association.UserDefinedPropertyName.CLIENT_CARDINALITY ) );
        this.deriveUpperCardinality();
        setContainingClass( (RwiNode) link.getDestination() );
        setRolesClassName( link.getSource( ).getProperty( RwiProperty.FULL_NAME ));
    }
}
