/* Generated by Together */

package com.togethersoft.modules.smartClient;

public interface CodeGenerator
{
	void generateCode( SupplierEnd aSupplierEnd);
	void generateCode( ClientEnd aClientEnd );
}
