/* Generated by Together */

package com.togethersoft.modules.smartClient;

public interface Literals
{
	public static String TO_MANY = "ToMany";
    public static String ONE_TO_MANY = "OneToMany";
    public static String TO_ONE = "ToOne";
    public static String MANY_TO_ONE = "ManyToOne";
    public static String ONE_TO_ONE = "OneToOne";
    public static String MANY_TO_MANY = "ManyToMany";
    public static String UNIDIRECTIONAL_TO_ONE = "UnidirectionalToOne";
    public static String UNIDIRECTIONAL_TO_MANY = "UnidirectionalToMany";
}
