/* Generated by Together */

package com.togethersoft.modules.smartClient;

public class ManyToOneGenerator extends CommonGenerator implements CodeGenerator
{
	public void generateCode( SupplierEnd aSupplierEnd )
    {
        adjustField( aSupplierEnd, Literals.TO_ONE, Literals.MANY_TO_ONE );
        if( aSupplierEnd.getField() != null )
        {
    		aSupplierEnd.getField().setProperty( Association.UserDefinedPropertyName.UNDIRECTED, true );
        }
        generateGetOne( aSupplierEnd );
        generateSetter( aSupplierEnd );
    }

	public void generateCode( ClientEnd aClientEnd )
    {
		adjustField( aClientEnd, Literals.TO_MANY, Literals.ONE_TO_MANY  );
        generateGetAll( aClientEnd );
        generateAdder( aClientEnd );
        generateRemoveOneOfMany( aClientEnd );
    }
}
