/* Generated by Together */

package com.togethersoft.modules.smartClient;

public class ManyToManyGenerator extends CommonGenerator implements CodeGenerator 
{
	public void generateCode( SupplierEnd aSupplierEnd )
    {
		adjustField( aSupplierEnd, Literals.TO_MANY, Literals.MANY_TO_MANY  );
        if( aSupplierEnd.getField() != null )
        {
    		aSupplierEnd.getField().setProperty( Association.UserDefinedPropertyName.UNDIRECTED, true );
        }
        generateGetAll( aSupplierEnd );
        generateAdder( aSupplierEnd );
        generateRemoveOneOfMany( aSupplierEnd );
    }

	public void generateCode( ClientEnd aClientEnd )
    {
		adjustField( aClientEnd, Literals.TO_MANY, Literals.MANY_TO_MANY  );
        generateGetAll( aClientEnd );
        generateAdder( aClientEnd );
        generateRemoveOneOfMany( aClientEnd );
    }
}
