/* Generated by Together */

package com.togethersoft.modules.smartClient;

public class OneToOneGenerator extends CommonGenerator implements CodeGenerator
{
	public void generateCode( SupplierEnd aSupplierEnd )
    {
        adjustField( aSupplierEnd, Literals.TO_ONE, Literals.ONE_TO_ONE );
        if( aSupplierEnd.getField() != null )
        {
    		aSupplierEnd.getField().setProperty( Association.UserDefinedPropertyName.UNDIRECTED, true );
        }
        generateGetOne( aSupplierEnd );
        generateSetter( aSupplierEnd );
    }

	public void generateCode( ClientEnd aClientEnd )
    {
        adjustField( aClientEnd, Literals.TO_ONE, Literals.ONE_TO_ONE );
        generateGetOne( aClientEnd );
        generateSetter( aClientEnd );
    }
}
