/* Generated by Together */

package com.togethersoft.modules.smartClient;

import com.togethersoft.openapi.rwi.RwiLink;
import com.togethersoft.openapi.rwi.RwiProperty;
import com.togethersoft.openapi.rwi.RwiModelAccess;
import com.togethersoft.openapi.rwi.RwiModel;
import com.togethersoft.openapi.rwi.RwiNode;
import com.togethersoft.openapi.rwi.RwiElement;

public class SupplierEnd extends AssociationEnd 
{

	public String toString()
    {
    	return " <<Supplier>> " + super.toString();
    }


	SupplierEnd( Association theAssociation )
    {
    	super( theAssociation );
    }

	AssociationEnd getOtherEnd()
    {
    	return getAssociation().getClientEnd();
    }

	void extractModelInfo( RwiLink link )
    {
    	RwiElement anElement = null;
		setRole( link.getProperty( Association.UserDefinedPropertyName.SUPPLIER_ROLE ) );
		setRawCardinality( link.getProperty( Association.UserDefinedPropertyName.SUPPLIER_CARDINALITY ) );
        this.deriveUpperCardinality();
        setContainingClass( (RwiNode) link.getSource() );
        setRolesClassName( link.getDestination( ).getProperty( RwiProperty.FULL_NAME ));
        anElement = RwiModelAccess.getModel().findElement( link.getProperty( RwiProperty.LINK_MEMBER ) );
        if( anElement != null )
        	setField( anElement );
    }
}
