/* Generated by Together */

package com.togethersoft.modules.smartClient;

public class ToManyGenerator extends CommonGenerator implements CodeGenerator
{
	public void generateCode( SupplierEnd aSupplierEnd )
    {
		adjustUnidirectionalField( aSupplierEnd, Literals.TO_MANY, Literals.UNIDIRECTIONAL_TO_MANY  );
        generateGetAll( aSupplierEnd );
        generateAdder( aSupplierEnd );
        generateRemoveOneOfMany( aSupplierEnd );
    }

	public void generateCode( ClientEnd aClientEnd )
    {
    	// No code is generated for this case.
    }
}
