/* Generated by Together */

package com.togethersoft.modules.smartClient;

public class ToOneGenerator extends CommonGenerator implements CodeGenerator
{
	public void generateCode( SupplierEnd aSupplierEnd )
    {
        adjustUnidirectionalField( aSupplierEnd, Literals.TO_ONE, Literals.UNIDIRECTIONAL_TO_ONE );
        generateGetOne( aSupplierEnd );
        generateSetter( aSupplierEnd );
    }

	public void generateCode( ClientEnd aClientEnd )
    {
    	// No code is generated for this case.
    }
}
